export interface Wishlist {
  bookId: string;
  userId: string;
}

export const wishlistData: Wishlist[] = [
  { bookId: "1", userId: "user1" },
  { bookId: "2", userId: "user1" },
  { bookId: "3", userId: "user2" },
  { bookId: "5", userId: "user2" },
  { bookId: "1", userId: "user3" },
  { bookId: "8", userId: "user1" },
  { bookId: "12", userId: "user4" },
  { bookId: "4", userId: "user5" },
  { bookId: "7", userId: "user2" },
  { bookId: "15", userId: "user1" },
  { bookId: "2", userId: "user3" },
  { bookId: "9", userId: "user4" },
  { bookId: "6", userId: "user5" },
  { bookId: "11", userId: "user1" },
  { bookId: "3", userId: "user2" },
  { bookId: "14", userId: "user3" },
  { bookId: "10", userId: "user4" },
  { bookId: "5", userId: "user5" },
  { bookId: "13", userId: "user1" },
  { bookId: "7", userId: "user2" },
  { bookId: "16", userId: "user3" },
  { bookId: "1", userId: "user4" },
  { bookId: "8", userId: "user5" },
  { bookId: "4", userId: "user1" },
  { bookId: "12", userId: "user2" },
  { bookId: "18", userId: "user3" },
  { bookId: "9", userId: "user4" },
  { bookId: "2", userId: "user5" },
  { bookId: "6", userId: "user1" },
  { bookId: "15", userId: "user2" },
  { bookId: "11", userId: "user3" },
  { bookId: "3", userId: "user4" },
  { bookId: "10", userId: "user5" },
  { bookId: "14", userId: "user1" },
  { bookId: "7", userId: "user2" },
  { bookId: "19", userId: "user3" },
  { bookId: "5", userId: "user4" },
  { bookId: "13", userId: "user5" },
  { bookId: "1", userId: "user1" },
  { bookId: "8", userId: "user2" },
  { bookId: "17", userId: "user3" },
  { bookId: "4", userId: "user4" },
  { bookId: "12", userId: "user5" },
  { bookId: "6", userId: "user1" },
  { bookId: "20", userId: "user2" },
  { bookId: "9", userId: "user3" },
  { bookId: "11", userId: "user4" },
  { bookId: "2", userId: "user5" },
  { bookId: "15", userId: "user1" },
  { bookId: "10", userId: "user2" },
];
